name: VanillaMessagesFormatter
version: '${version}'
main: ovh.unlimitedbytes.vanillamessagesformatter.VanillaMessagesFormatter
api-version: '1.20'
softdepend:
    - ProtocolLib
    - ProtocolSupport
    - ViaVersion
    - ViaBackwards
    - ViaRewind
    - Geyser-Spigot

commands:
    vanillamessagesformatter:
        aliases:
            - vmf
        description: 'VanillaMessagesFormatter command'
        usage: '/vanillamessagesformatter'
        permission: 'vanillamessagesformatter.info'

permissions:
    vanillamessagesformatter.info:
        description: 'VanillaMessagesFormatter info permission'
        default: true

    vanillamessagesformatter.reload:
        description: 'VanillaMessagesFormatter reload permission'
        default: op